server:
  port: 8761

spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
    enabled: true
    web:
      client:
        enabled: true
  application:
    name: discovery-service

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.springframework.cloud.sleuth: DEBUG

eureka:
  numberRegistrySyncRetries: 1
  instance:
    preferIpAddress: false
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true


